import { BaseGenerator, ComponentLibrary } from './base-generator.js';
import type { IGeneratedFile, IDesignContext, Architecture, StateManagement, Framework } from '../types.js';
import { createLogger } from '../logger.js';

const _logger = createLogger('angular-generator');

/**
 * Angular Generator - Generates Angular components and projects
 */
export class AngularGenerator extends BaseGenerator {
  constructor(framework: Framework) {
    super(framework);
  }

  generateProject(
    projectName: string,
    _architecture: Architecture,
    _stateManagement: StateManagement,
    _designContext: IDesignContext
  ): IGeneratedFile[] {
    this.logStart('project', projectName);

    // TODO: Implement Angular project generation
    const files: IGeneratedFile[] = [
      {
        path: 'README.md',
        content: `# ${projectName}\n\nAngular project generated by UIForge MCP.\n\nTODO: Implement Angular project generation.`,
      },
    ];

    this.logComplete('project', projectName, files.length);
    return files;
  }

  generateComponent(
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile[] {
    this.logStart('component', componentType);

    const componentName = this.formatComponentName(componentType);
    const files: IGeneratedFile[] = [];

    // Component file
    files.push(this.createComponentFile(componentName, componentType, props, designContext, componentLibrary));

    // Test file
    files.push(this.createTestFile(componentName, componentType, designContext, componentLibrary));

    this.logComplete('component', componentType, files.length);
    return files;
  }

  // Component Library Implementation Methods

  protected getShadcnDependencies(): string[] {
    return ['@radix-ui/themes', 'class-variance-authority'];
  }

  protected getRadixDependencies(): string[] {
    return ['@radix-ui/themes'];
  }

  protected getHeadlessUIDependencies(): string[] {
    return ['@headlessui/tailwindcss'];
  }

  protected getPrimeVueDependencies(): string[] {
    return [];
  }

  protected getMaterialDependencies(): string[] {
    return ['@angular/material'];
  }

  protected getShadcnImports(): string[] {
    return [];
  }

  protected getRadixImports(): string[] {
    return [];
  }

  protected getHeadlessUIImports(): string[] {
    return [];
  }

  protected getPrimeVueImports(): string[] {
    return [];
  }

  protected getMaterialImports(): string[] {
    return [];
  }

  protected generateShadcnComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4 bg-white rounded-lg shadow-md max-w-md">
      <h2 class="text-xl font-bold mb-2">${componentName}</h2>
      <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using shadcn/ui styles</p>
      <button class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">Click me</button>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  // TODO: Implement component logic
}`;
  }

  protected generateRadixComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <button (click)="openDialog()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">${componentName}</button>
      <div *ngIf="isDialogOpen" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
        <div class="bg-white p-6 rounded-lg shadow-lg max-w-md">
          <h3 class="text-lg font-bold mb-2">${componentName}</h3>
          <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using Radix UI patterns</p>
          <button (click)="closeDialog()" class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">Close</button>
        </div>
      </div>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  isDialogOpen = false;

  openDialog() {
    this.isDialogOpen = true;
  }

  closeDialog() {
    this.isDialogOpen = false;
  }
}`;
  }

  protected generateHeadlessUIComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <button (click)="toggleDialog()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">${componentName}</button>
      <div *ngIf="isDialogOpen" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
        <div class="bg-white p-6 rounded-lg shadow-lg max-w-md">
          <h3 class="text-lg font-bold mb-2">${componentName}</h3>
          <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using Headless UI patterns</p>
          <button (click)="toggleDialog()" class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">Close</button>
        </div>
      </div>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  isDialogOpen = false;

  toggleDialog() {
    this.isDialogOpen = !this.isDialogOpen;
  }
}`;
  }

  protected generatePrimeVueComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <button (click)="openDialog()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">
        <i class="fas fa-plus mr-2"></i>${componentName}
      </button>
      <div *ngIf="isDialogOpen" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
        <div class="bg-white p-6 rounded-lg shadow-lg max-w-md">
          <h3 class="text-lg font-bold mb-2">${componentName}</h3>
          <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using PrimeVue styles</p>
          <button (click)="closeDialog()" class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">
            <i class="fas fa-times mr-2"></i>Close
          </button>
        </div>
      </div>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  isDialogOpen = false;

  openDialog() {
    this.isDialogOpen = true;
  }

  closeDialog() {
    this.isDialogOpen = false;
  }
}`;
  }

  protected generateMaterialComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <mat-button (click)="openDialog()" color="primary" raised>${componentName}</mat-button>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  constructor(private dialog: MatDialog) {}

  openDialog() {
    this.dialog.open(DialogContentComponent, {
      data: { title: '${componentName}', message: 'A ${componentType.toLowerCase()} component using Material Design' }
    });
  }
}

@Component({
  selector: 'dialog-content',
  template: \`
    <div class="bg-white p-6 rounded-lg">
      <h2 mat-dialog-title>{{ data.title }}</h2>
      <div mat-dialog-content>{{ data.message }}</div>
      <div mat-dialog-actions>
        <button mat-button (click)="dialogRef.close()">Close</button>
      </div>
    </div>
  \`
})
export class DialogContentComponent {
  constructor(public dialogRef: any) {}
}`;
  }

  protected generateTailwindComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4 bg-white rounded-lg shadow-md">
      <h2 class="text-xl font-bold mb-4">${componentName}</h2>
      <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using Tailwind CSS</p>
      <button
        class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
        (click)="handleClick()"
      >
        Click me
      </button>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  handleClick() {
    console.log('Button clicked');
  }
}`;
  }

  private createComponentFile(
    componentName: string,
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    let content: string;

    if (componentLibrary && componentLibrary !== 'none') {
      content = this.generateComponentLibraryCode(componentType, props, componentLibrary);
    } else {
      content = this.generateTailwindComponent(componentType, props);
    }

    return {
      path: `src/app/components/${componentName}.component.ts`,
      content,
    };
  }

  private createTestFile(
    componentName: string,
    componentType: string,
    _designContext: IDesignContext,
    _componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    const content = `import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { ${componentName}Component } from './${componentName}.component';

describe('${componentName}Component', () => {
  let component: ${componentName}Component;
  let fixture: ComponentFixture<${componentName}Component>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [${componentName}Component]
    }).compileComponents();

    fixture = TestBed.createComponent(${componentName}Component);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should render component type', () => {
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.textContent).toContain('${componentType.toLowerCase()}');
  });
});
`;

    return {
      path: `src/app/components/${componentName}.component.spec.ts`,
      content,
    };
  }
}
