import { BaseGenerator, ComponentLibrary } from './base-generator.js';
import type { IGeneratedFile, IDesignContext, Architecture, StateManagement, Framework } from '../types.js';
import { createLogger } from '../logger.js';

const _logger = createLogger('html-generator');

/**
 * HTML Generator - Generates HTML components and projects
 */
export class HtmlGenerator extends BaseGenerator {
  constructor(framework: Framework) {
    super(framework);
  }

  generateProject(
    projectName: string,
    _architecture: Architecture,
    _stateManagement: StateManagement,
    _designContext: IDesignContext
  ): IGeneratedFile[] {
    this.logStart('project', projectName);

    // TODO: Implement HTML project generation
    const files: IGeneratedFile[] = [
      {
        path: 'README.md',
        content: `# ${projectName}\n\nHTML project generated by UIForge MCP.\n\nTODO: Implement HTML project generation.`,
      },
    ];

    this.logComplete('project', projectName, files.length);
    return files;
  }

  generateComponent(
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile[] {
    this.logStart('component', componentType);

    const componentName = this.formatComponentName(componentType);
    const files: IGeneratedFile[] = [];

    // Component file
    files.push(this.createComponentFile(componentName, componentType, props, designContext, componentLibrary));

    this.logComplete('component', componentType, files.length);
    return files;
  }

  // Component Library Implementation Methods

  protected getShadcnDependencies(): string[] {
    return ['class-variance-authority', 'clsx', 'tailwind-merge'];
  }

  protected getRadixDependencies(): string[] {
    return [];
  }

  protected getHeadlessUIDependencies(): string[] {
    return [];
  }

  protected getPrimeVueDependencies(): string[] {
    return [];
  }

  protected getMaterialDependencies(): string[] {
    return [];
  }

  protected getShadcnImports(): string[] {
    return [];
  }

  protected getRadixImports(): string[] {
    return [];
  }

  protected getHeadlessUIImports(): string[] {
    return [];
  }

  protected getPrimeVueImports(): string[] {
    return [];
  }

  protected getMaterialImports(): string[] {
    return [];
  }

  protected generateShadcnComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${componentName}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    function cn(...classes) {
      return classes.filter(Boolean).join(' ');
    }
  </script>
</head>
<body>
  <div class="w-full max-w-md p-4 bg-white rounded-lg shadow-md">
    <h2 class="text-xl font-bold mb-2">${componentName}</h2>
    <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component built with shadcn/ui styles</p>
    <button class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">Click me</button>
  </div>
</body>
</html>`;
  }

  protected generateRadixComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${componentName}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <div class="p-4">
    <button onclick="openDialog()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">${componentName}</button>
    <div id="dialog" class="hidden fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div class="bg-white p-6 rounded-lg shadow-lg max-w-md">
        <h3 class="text-lg font-bold mb-2">${componentName}</h3>
        <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using Radix UI patterns</p>
        <button onclick="closeDialog()" class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">Close</button>
      </div>
    </div>
  </div>
  <script>
    function openDialog() {
      document.getElementById('dialog').classList.remove('hidden');
    }
    function closeDialog() {
      document.getElementById('dialog').classList.add('hidden');
    }
  </script>
</body>
</html>`;
  }

  protected generateHeadlessUIComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${componentName}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <div class="p-4">
    <button onclick="toggleDialog()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">${componentName}</button>
    <div id="dialog" class="hidden fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div class="bg-white p-6 rounded-lg shadow-lg max-w-md">
        <h3 class="text-lg font-bold mb-2">${componentName}</h3>
        <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using Headless UI patterns</p>
        <button onclick="toggleDialog()" class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">Close</button>
      </div>
    </div>
  </div>
  <script>
    function toggleDialog() {
      const dialog = document.getElementById('dialog');
      dialog.classList.toggle('hidden');
    }
  </script>
</body>
</html>`;
  }

  protected generatePrimeVueComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${componentName}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>
<body>
  <div class="p-4">
    <button onclick="openDialog()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">
      <i class="fas fa-plus mr-2"></i>${componentName}
    </button>
    <div id="dialog" class="hidden fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div class="bg-white p-6 rounded-lg shadow-lg max-w-md">
        <h3 class="text-lg font-bold mb-2">${componentName}</h3>
        <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using PrimeVue styles</p>
        <button onclick="closeDialog()" class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">
          <i class="fas fa-times mr-2"></i>Close
        </button>
      </div>
    </div>
  </div>
  <script>
    function openDialog() {
      document.getElementById('dialog').classList.remove('hidden');
    }
    function closeDialog() {
      document.getElementById('dialog').classList.add('hidden');
    }
  </script>
</body>
</html>`;
  }

  protected generateMaterialComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${componentName}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Roboto', sans-serif; }
  </style>
</head>
<body>
  <div class="p-4">
    <button onclick="openDialog()" class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded shadow-md">${componentName}</button>
    <div id="dialog" class="hidden fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div class="bg-white p-6 rounded-lg shadow-xl max-w-md">
        <h3 class="text-xl font-medium mb-2">${componentName}</h3>
        <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using Material Design</p>
        <button onclick="closeDialog()" class="bg-gray-600 hover:bg-gray-700 text-white px-4 py-2 rounded">Close</button>
      </div>
    </div>
  </div>
  <script>
    function openDialog() {
      document.getElementById('dialog').classList.remove('hidden');
    }
    function closeDialog() {
      document.getElementById('dialog').classList.add('hidden');
    }
  </script>
</body>
</html>`;
  }

  protected generateTailwindComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${componentName}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <div class="p-4 bg-white rounded-lg shadow-md">
    <h2 class="text-xl font-bold mb-4">${componentName}</h2>
    <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using Tailwind CSS</p>
    <button
      class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
      onclick="console.log('Button clicked')"
    >
      Click me
    </button>
  </div>
</body>
</html>`;
  }

  private createComponentFile(
    componentName: string,
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    let content: string;

    if (componentLibrary && componentLibrary !== 'none') {
      content = this.generateComponentLibraryCode(componentType, props, componentLibrary);
    } else {
      content = this.generateTailwindComponent(componentType, props);
    }

    return {
      path: `src/components/${componentName}.html`,
      content,
    };
  }
}
