import { BaseGenerator, ComponentLibrary } from './base-generator.js';
import type { IGeneratedFile, IDesignContext, Architecture, StateManagement, Framework } from '../types.js';
import { createLogger } from '../logger.js';

const _logger = createLogger('svelte-generator');

/**
 * Svelte Generator - Generates Svelte components and projects
 */
export class SvelteGenerator extends BaseGenerator {
  constructor(framework: Framework) {
    super(framework);
  }

  generateProject(
    projectName: string,
    _architecture: Architecture,
    _stateManagement: StateManagement,
    _designContext: IDesignContext
  ): IGeneratedFile[] {
    this.logStart('project', projectName);

    // TODO: Implement Svelte project generation
    const files: IGeneratedFile[] = [
      {
        path: 'README.md',
        content: `# ${projectName}\n\nSvelte project generated by UIForge MCP.\n\nTODO: Implement Svelte project generation.`,
      },
    ];

    this.logComplete('project', projectName, files.length);
    return files;
  }

  generateComponent(
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile[] {
    this.logStart('component', componentType);

    const componentName = this.formatComponentName(componentType);
    const files: IGeneratedFile[] = [];

    // Component file
    files.push(this.createComponentFile(componentName, componentType, props, designContext, componentLibrary));

    // Test file
    files.push(this.createTestFile(componentName, componentType, designContext, componentLibrary));

    this.logComplete('component', componentType, files.length);
    return files;
  }

  // Component Library Implementation Methods

  protected getShadcnDependencies(): string[] {
    return ['bits-ui', 'class-variance-authority', 'clsx', 'tailwind-merge'];
  }

  protected getRadixDependencies(): string[] {
    return ['@radix-ui/svelte'];
  }

  protected getHeadlessUIDependencies(): string[] {
    return ['@headlessui/svelte'];
  }

  protected getPrimeVueDependencies(): string[] {
    return [];
  }

  protected getMaterialDependencies(): string[] {
    return ['@smui/material'];
  }

  protected getShadcnImports(): string[] {
    return [];
  }

  protected getRadixImports(): string[] {
    return [];
  }

  protected getHeadlessUIImports(): string[] {
    return [];
  }

  protected getPrimeVueImports(): string[] {
    return [];
  }

  protected getMaterialImports(): string[] {
    return [];
  }

  protected generateShadcnComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<script lang="ts">
  import { Button } from "$lib/components/ui/button";
  import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "$lib/components/ui/card";
  import { cn } from "$lib/utils";

  export let className = '';
</script>

<Card class={cn('w-full max-w-md', className)}>
  <CardHeader>
    <CardTitle>${componentName}</CardTitle>
    <CardDescription>
      A ${componentType.toLowerCase()} component built with shadcn/ui
    </CardDescription>
  </CardHeader>
  <CardContent>
    <p>This is a ${componentType.toLowerCase()} component using shadcn/ui design system.</p>
    <Button class="mt-4">Click me</Button>
  </CardContent>
</Card>`;
  }

  protected generateRadixComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<script lang="ts">
  import * as Dialog from "@radix-ui/svelte/dialog";
  import * as DropdownMenu from "@radix-ui/svelte/dropdown-menu";

  let open = false;
</script>

<Dialog.Root bind:open>
  <Dialog.Trigger asChild let:builder>
    <button builders={builder}>${componentName}</button>
  </Dialog.Trigger>
  <Dialog.Portal>
    <Dialog.Overlay class="fixed inset-0 bg-black/50" />
    <Dialog.Content class="fixed left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-white p-6 rounded-lg shadow-lg">
      <Dialog.Title>${componentName}</Dialog.Title>
      <Dialog.Description>
        A ${componentType.toLowerCase()} component using Radix UI primitives
      </Dialog.Description>
      <DropdownMenu.Root>
        <DropdownMenu.Trigger asChild let:builder>
          <button builders={builder}>Options</button>
        </DropdownMenu.Trigger>
        <DropdownMenu.Portal>
          <DropdownMenu.Content class="bg-white p-2 rounded-lg shadow-lg">
            <DropdownMenu.Item>Option 1</DropdownMenu.Item>
            <DropdownMenu.Item>Option 2</DropdownMenu.Item>
          </DropdownMenu.Content>
        </DropdownMenu.Portal>
      </DropdownMenu.Root>
    </Dialog.Content>
  </Dialog.Portal>
</Dialog.Root>`;
  }

  protected generateHeadlessUIComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<script lang="ts">
  import { Button } from "@headlessui/svelte";
  import { Dialog } from "@headlessui/svelte";

  let open = false;

  function handleClick() {
    open = true;
  }

  function handleClose() {
    open = false;
  }
</script>

<div class="p-4">
  <Button onClick={handleClick}>${componentName}</Button>
  <Dialog bind:open onClose={handleClose}>
    <Dialog.Panel class="fixed inset-0 bg-white p-6 rounded-lg shadow-lg">
      <Dialog.Title>${componentName}</Dialog.Title>
      <Dialog.Description>
        A ${componentType.toLowerCase()} component using Headless UI
      </Dialog.Description>
      <div class="mt-4">
        <Button onClick={handleClose}>Close</Button>
      </div>
    </Dialog.Panel>
  </Dialog>
</div>`;
  }

  protected generatePrimeVueComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<script lang="ts">
  let visible = false;

  function handleClick() {
    visible = true;
  }

  function handleClose() {
    visible = false;
  }
</script>

<div class="p-4">
  <button on:click={handleClick} class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">
    <i class="fas fa-plus mr-2"></i>${componentName}
  </button>
  {#if visible}
    <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div class="bg-white p-6 rounded-lg shadow-lg max-w-md">
        <h3 class="text-lg font-bold mb-2">${componentName}</h3>
        <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using PrimeVue styles</p>
        <button on:click={handleClose} class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">
          <i class="fas fa-times mr-2"></i>Close
        </button>
      </div>
    </div>
  {/if}
</div>`;
  }

  protected generateMaterialComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<script lang="ts">
  import { Button } from "@smui/button";
  import { Dialog, DialogTitle, DialogContent, DialogActions } from "@smui/dialog";

  let open = false;

  function handleClick() {
    open = true;
  }

  function handleClose() {
    open = false;
  }
</script>

<div class="p-4">
  <Button variant="raised" on:click={handleClick}>
    ${componentName}
  </Button>
  <Dialog bind:open on:close={handleClose}>
    <DialogTitle>${componentName}</DialogTitle>
    <DialogContent>
      <p>A ${componentType.toLowerCase()} component using Material Design</p>
    </DialogContent>
    <DialogActions>
      <Button on:click={handleClose}>Close</Button>
    </DialogActions>
  </Dialog>
</div>`;
  }

  protected generateTailwindComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `<script lang="ts">
  function handleClick() {
    console.log('Button clicked');
  }
</script>

<div class="p-4 bg-white rounded-lg shadow-md">
  <h2 class="text-xl font-bold mb-4">${componentName}</h2>
  <p class="text-gray-600 mb-4">
    A ${componentType.toLowerCase()} component using Tailwind CSS
  </p>
  <button
    class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
    on:click={handleClick}
  >
    Click me
  </button>
</div>`;
  }

  private createComponentFile(
    componentName: string,
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    let content: string;

    if (componentLibrary && componentLibrary !== 'none') {
      content = this.generateComponentLibraryCode(componentType, props, componentLibrary);
    } else {
      content = this.generateTailwindComponent(componentType, props);
    }

    return {
      path: `src/lib/components/${componentName}.svelte`,
      content,
    };
  }

  private createTestFile(
    componentName: string,
    componentType: string,
    _designContext: IDesignContext,
    _componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    const content = `import { render, screen } from '@testing-library/svelte';
import { describe, it, expect } from 'vitest';
import ${componentName} from './${componentName}.svelte';

describe('${componentName}', () => {
  it('renders without crashing', () => {
    render(${componentName});
    expect(screen.getByText('${componentName}')).toBeInTheDocument();
  });

  it('displays the component type', () => {
    render(${componentName});
    expect(screen.getByText(/${componentType.toLowerCase()}/i)).toBeInTheDocument();
  });
});
`;

    return {
      path: `src/lib/components/${componentName}.test.ts`,
      content,
    };
  }
}
