import { BaseGenerator, ComponentLibrary } from './base-generator.js';
import type { IGeneratedFile, IDesignContext, Architecture, StateManagement, Framework } from '../types.js';
import { createLogger } from '../logger.js';

const logger = createLogger('vue-generator');

/**
 * Vue Generator - Generates Vue components and projects
 */
export class VueGenerator extends BaseGenerator {
  constructor(framework: Framework) {
    super(framework);
  }

  generateProject(
    projectName: string,
    architecture: Architecture,
    stateManagement: StateManagement,
    designContext: IDesignContext
  ): IGeneratedFile[] {
    this.logStart('project', projectName);

    // TODO: Implement Vue project generation
    const files: IGeneratedFile[] = [
      {
        path: 'README.md',
        content: `# ${projectName}\n\nVue project generated by UIForge MCP.\n\nTODO: Implement Vue project generation.`,
      },
    ];

    this.logComplete('project', projectName, files.length);
    return files;
  }

  generateComponent(
    componentType: string,
    props: Record<string, any>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile[] {
    this.logStart('component', componentType);

    const componentName = this.formatComponentName(componentType);
    const files: IGeneratedFile[] = [];

    // Component file
    files.push(this.createComponentFile(componentName, componentType, props, designContext, componentLibrary));

    // Test file
    files.push(this.createTestFile(componentName, componentType, designContext, componentLibrary));

    this.logComplete('component', componentType, files.length);
    return files;
  }

  // Component Library Implementation Methods

  protected getShadcnDependencies(): string[] {
    return ['@radix-ui/vue-slot', 'class-variance-authority', 'clsx', 'tailwind-merge', 'lucide-vue-next'];
  }

  protected getRadixDependencies(): string[] {
    return [
      '@radix-ui/vue-slot',
      '@radix-ui/vue-dialog',
      '@radix-ui/vue-dropdown-menu',
      '@radix-ui/vue-select',
      '@radix-ui/vue-tabs',
    ];
  }

  protected getHeadlessUIDependencies(): string[] {
    return ['@headlessui/vue', '@heroicons/vue'];
  }

  protected getPrimeVueDependencies(): string[] {
    return ['primevue', 'primeicons'];
  }

  protected getMaterialDependencies(): string[] {
    return ['@mui/material', '@mui/icons-material'];
  }

  protected getShadcnImports(): string[] {
    return [
      'import { cn } from "@/lib/utils"',
      'import { Button } from "@/components/ui/button"',
      'import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"',
    ];
  }

  protected getRadixImports(): string[] {
    return [
      'import * as Dialog from "@radix-ui/vue-dialog"',
      'import * as DropdownMenu from "@radix-ui/vue-dropdown-menu"',
      'import * as Select from "@radix-ui/vue-select"',
      'import * as Tabs from "@radix-ui/vue-tabs"',
    ];
  }

  protected getHeadlessUIImports(): string[] {
    return [
      'import { Button } from "@headlessui/vue"',
      'import { Dialog } from "@headlessui/vue"',
      'import { Menu } from "@headlessui/vue"',
    ];
  }

  protected getPrimeVueImports(): string[] {
    return [
      'import Button from "primevue/button"',
      'import Dialog from "primevue/dialog"',
      'import InputText from "primevue/inputtext"',
      'import DataTable from "primevue/datatable"',
    ];
  }

  protected getMaterialImports(): string[] {
    return [
      'import { Button } from "@mui/material/Button"',
      'import { Dialog } from "@mui/material/Dialog"',
      'import { TextField } from "@mui/material/TextField"',
      'import { Card } from "@mui/material/Card"',
    ];
  }

  protected generateShadcnComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <Card :class="cn('w-full max-w-md', props.className)">
    <CardHeader>
      <CardTitle>${componentName}</CardTitle>
      <CardDescription>
        A ${componentType.toLowerCase()} component built with shadcn/ui
      </CardDescription>
    </CardHeader>
    <CardContent>
      <p>This is a ${componentType.toLowerCase()} component using shadcn/ui design system.</p>
      <Button class="mt-4">Click me</Button>
    </CardContent>
  </Card>
</template>

<script setup lang="ts">
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"

interface Props {
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  className: ''
})
</script>`;
  }

  protected generateRadixComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <Dialog.Root>
    <Dialog.Trigger as-child>
      <button>${componentName}</button>
    </Dialog.Trigger>
    <Dialog.Portal>
      <Dialog.Overlay class="fixed inset-0 bg-black/50" />
      <Dialog.Content class="fixed left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-white p-6 rounded-lg shadow-lg">
        <Dialog.Title>${componentName}</Dialog.Title>
        <Dialog.Description>
          A ${componentType.toLowerCase()} component using Radix UI primitives
        </Dialog.Description>
        <DropdownMenu.Root>
          <DropdownMenu.Trigger as-child>
            <button>Options</button>
          </DropdownMenu.Trigger>
          <DropdownMenu.Portal>
            <DropdownMenu.Content class="bg-white p-2 rounded-lg shadow-lg">
              <DropdownMenu.Item>Option 1</DropdownMenu.Item>
              <DropdownMenu.Item>Option 2</DropdownMenu.Item>
            </DropdownMenu.Content>
          </DropdownMenu.Portal>
        </DropdownMenu.Root>
      </Dialog.Content>
    </Dialog.Portal>
  </Dialog.Root>
</template>

<script setup lang="ts">
import * as Dialog from "@radix-ui/vue-dialog"
import * as DropdownMenu from "@radix-ui/vue-dropdown-menu"
</script>`;
  }

  protected generateHeadlessUIComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <div class="p-4">
    <Button @click="handleClick">${componentName}</Button>
    <Dialog :open="open" @close="handleClose">
      <Dialog.Panel class="fixed inset-0 bg-white p-6 rounded-lg shadow-lg">
        <Dialog.Title>${componentName}</Dialog.Title>
        <Dialog.Description>
          A ${componentType.toLowerCase()} component using Headless UI
        </Dialog.Description>
        <div class="mt-4">
          <Button @click="handleClose">Close</Button>
        </div>
      </Dialog.Panel>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Button } from "@headlessui/vue"
import { Dialog } from "@headlessui/vue"

const open = ref(false)

const handleClick = () => {
  open.value = true
}

const handleClose = () => {
  open.value = false
}
</script>`;
  }

  protected generatePrimeVueComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <div class="p-4">
    <Button :label="${componentName}" @click="handleClick" />
    <Dialog v-model:visible="visible" modal header="${componentName}">
      <p class="mb-4">A ${componentType.toLowerCase()} component using PrimeVue</p>
      <Button label="Close" @click="visible = false" />
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'

const visible = ref(false)

const handleClick = () => {
  visible.value = true
}
</script>`;
  }

  protected generateMaterialComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <div class="p-4">
    <Button variant="contained" @click="handleClick">
      ${componentName}
    </Button>
    <Dialog v-model="open" @update:model-value="handleClose">
      <DialogTitle>${componentName}</DialogTitle>
      <DialogContent>
        <p>A ${componentType.toLowerCase()} component using Material UI</p>
      </DialogContent>
      <DialogActions>
        <Button @click="handleClose">Close</Button>
      </DialogActions>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Button } from "@mui/material/Button"
import { Dialog, DialogTitle, DialogContent, DialogActions } from "@mui/material/Dialog"

const open = ref(false)

const handleClick = () => {
  open.value = true
}

const handleClose = () => {
  open.value = false
}
</script>`;
  }

  protected generateTailwindComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `<template>
  <div class="p-4 bg-white rounded-lg shadow-md">
    <h2 class="text-xl font-bold mb-4">${componentName}</h2>
    <p class="text-gray-600 mb-4">
      A ${componentType.toLowerCase()} component using Tailwind CSS
    </p>
    <button
      class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
      @click="handleClick"
    >
      Click me
    </button>
  </div>
</template>

<script setup lang="ts">
const handleClick = () => {
  console.log('Button clicked')
}
</script>`;
  }

  private createComponentFile(
    componentName: string,
    componentType: string,
    props: Record<string, any>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    let content: string;

    if (componentLibrary && componentLibrary !== 'none') {
      // Use component library-specific generation
      content = this.generateComponentLibraryCode(componentType, props, componentLibrary);
    } else {
      // Use default Tailwind CSS generation
      content = this.generateTailwindComponent(componentType, props);
    }

    return {
      path: `src/components/${componentName}.vue`,
      content,
    };
  }

  private createTestFile(
    componentName: string,
    componentType: string,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    const content = `import { mount } from '@vue/test-utils'
import { describe, it, expect } from 'vitest'
import ${componentName} from './${componentName}.vue'

describe('${componentName}', () => {
  it('renders without crashing', () => {
    const wrapper = mount(${componentName})
    expect(wrapper.exists()).toBe(true)
  })

  it('displays the component type', () => {
    const wrapper = mount(${componentName})
    expect(wrapper.text()).toMatch(/${componentType.toLowerCase()}/i)
  })
})
`;

    return {
      path: `src/components/${componentName}.test.ts`,
      content,
    };
  }
}
