import type { IIconMapping } from '../types.js';

export const lucideMappings: IIconMapping[] = [
  {
    generic: 'arrow-right',
    lucide: 'ArrowRight',
    heroicons: 'ArrowRightIcon',
    phosphor: 'ArrowRight',
    tabler: 'IconArrowRight',
    fontAwesome: 'faArrowRight',
    radix: 'ArrowRightIcon',
  },
  {
    generic: 'arrow-left',
    lucide: 'ArrowLeft',
    heroicons: 'ArrowLeftIcon',
    phosphor: 'ArrowLeft',
    tabler: 'IconArrowLeft',
    fontAwesome: 'faArrowLeft',
    radix: 'ArrowLeftIcon',
  },
  {
    generic: 'arrow-up',
    lucide: 'ArrowUp',
    heroicons: 'ArrowUpIcon',
    phosphor: 'ArrowUp',
    tabler: 'IconArrowUp',
    fontAwesome: 'faArrowUp',
    radix: 'ArrowUpIcon',
  },
  {
    generic: 'arrow-down',
    lucide: 'ArrowDown',
    heroicons: 'ArrowDownIcon',
    phosphor: 'ArrowDown',
    tabler: 'IconArrowDown',
    fontAwesome: 'faArrowDown',
    radix: 'ArrowDownIcon',
  },
  {
    generic: 'check',
    lucide: 'Check',
    heroicons: 'CheckIcon',
    phosphor: 'Check',
    tabler: 'IconCheck',
    fontAwesome: 'faCheck',
    radix: 'CheckIcon',
  },
  {
    generic: 'x',
    lucide: 'X',
    heroicons: 'XMarkIcon',
    phosphor: 'X',
    tabler: 'IconX',
    fontAwesome: 'faXmark',
    radix: 'Cross2Icon',
  },
  {
    generic: 'menu',
    lucide: 'Menu',
    heroicons: 'Bars3Icon',
    phosphor: 'List',
    tabler: 'IconMenu2',
    fontAwesome: 'faBars',
    radix: 'HamburgerMenuIcon',
  },
  {
    generic: 'search',
    lucide: 'Search',
    heroicons: 'MagnifyingGlassIcon',
    phosphor: 'MagnifyingGlass',
    tabler: 'IconSearch',
    fontAwesome: 'faMagnifyingGlass',
    radix: 'MagnifyingGlassIcon',
  },
  {
    generic: 'settings',
    lucide: 'Settings',
    heroicons: 'Cog6ToothIcon',
    phosphor: 'Gear',
    tabler: 'IconSettings',
    fontAwesome: 'faGear',
    radix: 'GearIcon',
  },
  {
    generic: 'user',
    lucide: 'User',
    heroicons: 'UserIcon',
    phosphor: 'User',
    tabler: 'IconUser',
    fontAwesome: 'faUser',
    radix: 'PersonIcon',
  },
  {
    generic: 'home',
    lucide: 'Home',
    heroicons: 'HomeIcon',
    phosphor: 'House',
    tabler: 'IconHome',
    fontAwesome: 'faHouse',
    radix: 'HomeIcon',
  },
  {
    generic: 'mail',
    lucide: 'Mail',
    heroicons: 'EnvelopeIcon',
    phosphor: 'Envelope',
    tabler: 'IconMail',
    fontAwesome: 'faEnvelope',
    radix: 'EnvelopeClosedIcon',
  },
  {
    generic: 'phone',
    lucide: 'Phone',
    heroicons: 'PhoneIcon',
    phosphor: 'Phone',
    tabler: 'IconPhone',
    fontAwesome: 'faPhone',
    radix: 'MobileIcon',
  },
  {
    generic: 'calendar',
    lucide: 'Calendar',
    heroicons: 'CalendarIcon',
    phosphor: 'Calendar',
    tabler: 'IconCalendar',
    fontAwesome: 'faCalendar',
    radix: 'CalendarIcon',
  },
  {
    generic: 'clock',
    lucide: 'Clock',
    heroicons: 'ClockIcon',
    phosphor: 'Clock',
    tabler: 'IconClock',
    fontAwesome: 'faClock',
    radix: 'ClockIcon',
  },
  {
    generic: 'star',
    lucide: 'Star',
    heroicons: 'StarIcon',
    phosphor: 'Star',
    tabler: 'IconStar',
    fontAwesome: 'faStar',
    radix: 'StarIcon',
  },
  {
    generic: 'heart',
    lucide: 'Heart',
    heroicons: 'HeartIcon',
    phosphor: 'Heart',
    tabler: 'IconHeart',
    fontAwesome: 'faHeart',
    radix: 'HeartIcon',
  },
  {
    generic: 'trash',
    lucide: 'Trash2',
    heroicons: 'TrashIcon',
    phosphor: 'Trash',
    tabler: 'IconTrash',
    fontAwesome: 'faTrash',
    radix: 'TrashIcon',
  },
  {
    generic: 'edit',
    lucide: 'Edit',
    heroicons: 'PencilIcon',
    phosphor: 'Pencil',
    tabler: 'IconEdit',
    fontAwesome: 'faPencil',
    radix: 'Pencil1Icon',
  },
  {
    generic: 'plus',
    lucide: 'Plus',
    heroicons: 'PlusIcon',
    phosphor: 'Plus',
    tabler: 'IconPlus',
    fontAwesome: 'faPlus',
    radix: 'PlusIcon',
  },
  {
    generic: 'minus',
    lucide: 'Minus',
    heroicons: 'MinusIcon',
    phosphor: 'Minus',
    tabler: 'IconMinus',
    fontAwesome: 'faMinus',
    radix: 'MinusIcon',
  },
  {
    generic: 'eye',
    lucide: 'Eye',
    heroicons: 'EyeIcon',
    phosphor: 'Eye',
    tabler: 'IconEye',
    fontAwesome: 'faEye',
    radix: 'EyeOpenIcon',
  },
  {
    generic: 'eye-off',
    lucide: 'EyeOff',
    heroicons: 'EyeSlashIcon',
    phosphor: 'EyeSlash',
    tabler: 'IconEyeOff',
    fontAwesome: 'faEyeSlash',
    radix: 'EyeClosedIcon',
  },
  {
    generic: 'lock',
    lucide: 'Lock',
    heroicons: 'LockClosedIcon',
    phosphor: 'Lock',
    tabler: 'IconLock',
    fontAwesome: 'faLock',
    radix: 'LockClosedIcon',
  },
  {
    generic: 'unlock',
    lucide: 'Unlock',
    heroicons: 'LockOpenIcon',
    phosphor: 'LockOpen',
    tabler: 'IconLockOpen',
    fontAwesome: 'faLockOpen',
    radix: 'LockOpen1Icon',
  },
  {
    generic: 'download',
    lucide: 'Download',
    heroicons: 'ArrowDownTrayIcon',
    phosphor: 'Download',
    tabler: 'IconDownload',
    fontAwesome: 'faDownload',
    radix: 'DownloadIcon',
  },
  {
    generic: 'upload',
    lucide: 'Upload',
    heroicons: 'ArrowUpTrayIcon',
    phosphor: 'Upload',
    tabler: 'IconUpload',
    fontAwesome: 'faUpload',
    radix: 'UploadIcon',
  },
  {
    generic: 'share',
    lucide: 'Share2',
    heroicons: 'ShareIcon',
    phosphor: 'Share',
    tabler: 'IconShare',
    fontAwesome: 'faShare',
    radix: 'Share1Icon',
  },
  {
    generic: 'link',
    lucide: 'Link',
    heroicons: 'LinkIcon',
    phosphor: 'Link',
    tabler: 'IconLink',
    fontAwesome: 'faLink',
    radix: 'Link2Icon',
  },
  {
    generic: 'external-link',
    lucide: 'ExternalLink',
    heroicons: 'ArrowTopRightOnSquareIcon',
    phosphor: 'ArrowSquareOut',
    tabler: 'IconExternalLink',
    fontAwesome: 'faArrowUpRightFromSquare',
    radix: 'ExternalLinkIcon',
  },
  {
    generic: 'copy',
    lucide: 'Copy',
    heroicons: 'DocumentDuplicateIcon',
    phosphor: 'Copy',
    tabler: 'IconCopy',
    fontAwesome: 'faCopy',
    radix: 'CopyIcon',
  },
  {
    generic: 'clipboard',
    lucide: 'Clipboard',
    heroicons: 'ClipboardIcon',
    phosphor: 'Clipboard',
    tabler: 'IconClipboard',
    fontAwesome: 'faClipboard',
    radix: 'ClipboardIcon',
  },
  {
    generic: 'bell',
    lucide: 'Bell',
    heroicons: 'BellIcon',
    phosphor: 'Bell',
    tabler: 'IconBell',
    fontAwesome: 'faBell',
    radix: 'BellIcon',
  },
  {
    generic: 'sun',
    lucide: 'Sun',
    heroicons: 'SunIcon',
    phosphor: 'Sun',
    tabler: 'IconSun',
    fontAwesome: 'faSun',
    radix: 'SunIcon',
  },
  {
    generic: 'moon',
    lucide: 'Moon',
    heroicons: 'MoonIcon',
    phosphor: 'Moon',
    tabler: 'IconMoon',
    fontAwesome: 'faMoon',
    radix: 'MoonIcon',
  },
  {
    generic: 'filter',
    lucide: 'Filter',
    heroicons: 'FunnelIcon',
    phosphor: 'Funnel',
    tabler: 'IconFilter',
    fontAwesome: 'faFilter',
    radix: 'MixerHorizontalIcon',
  },
  {
    generic: 'sort',
    lucide: 'ArrowUpDown',
    heroicons: 'ArrowsUpDownIcon',
    phosphor: 'ArrowsDownUp',
    tabler: 'IconArrowsSort',
    fontAwesome: 'faSort',
    radix: 'MixIcon',
  },
  {
    generic: 'refresh',
    lucide: 'RefreshCw',
    heroicons: 'ArrowPathIcon',
    phosphor: 'ArrowClockwise',
    tabler: 'IconRefresh',
    fontAwesome: 'faArrowsRotate',
    radix: 'ReloadIcon',
  },
  {
    generic: 'chevron-down',
    lucide: 'ChevronDown',
    heroicons: 'ChevronDownIcon',
    phosphor: 'CaretDown',
    tabler: 'IconChevronDown',
    fontAwesome: 'faChevronDown',
    radix: 'ChevronDownIcon',
  },
  {
    generic: 'chevron-up',
    lucide: 'ChevronUp',
    heroicons: 'ChevronUpIcon',
    phosphor: 'CaretUp',
    tabler: 'IconChevronUp',
    fontAwesome: 'faChevronUp',
    radix: 'ChevronUpIcon',
  },
  {
    generic: 'chevron-left',
    lucide: 'ChevronLeft',
    heroicons: 'ChevronLeftIcon',
    phosphor: 'CaretLeft',
    tabler: 'IconChevronLeft',
    fontAwesome: 'faChevronLeft',
    radix: 'ChevronLeftIcon',
  },
  {
    generic: 'chevron-right',
    lucide: 'ChevronRight',
    heroicons: 'ChevronRightIcon',
    phosphor: 'CaretRight',
    tabler: 'IconChevronRight',
    fontAwesome: 'faChevronRight',
    radix: 'ChevronRightIcon',
  },
  {
    generic: 'info',
    lucide: 'Info',
    heroicons: 'InformationCircleIcon',
    phosphor: 'Info',
    tabler: 'IconInfoCircle',
    fontAwesome: 'faCircleInfo',
    radix: 'InfoCircledIcon',
  },
  {
    generic: 'warning',
    lucide: 'AlertTriangle',
    heroicons: 'ExclamationTriangleIcon',
    phosphor: 'Warning',
    tabler: 'IconAlertTriangle',
    fontAwesome: 'faTriangleExclamation',
    radix: 'ExclamationTriangleIcon',
  },
  {
    generic: 'error',
    lucide: 'AlertCircle',
    heroicons: 'ExclamationCircleIcon',
    phosphor: 'WarningCircle',
    tabler: 'IconAlertCircle',
    fontAwesome: 'faCircleExclamation',
    radix: 'CrossCircledIcon',
  },
  {
    generic: 'success',
    lucide: 'CheckCircle2',
    heroicons: 'CheckCircleIcon',
    phosphor: 'CheckCircle',
    tabler: 'IconCircleCheck',
    fontAwesome: 'faCircleCheck',
    radix: 'CheckCircledIcon',
  },
  {
    generic: 'loading',
    lucide: 'Loader2',
    heroicons: 'ArrowPathIcon',
    phosphor: 'CircleNotch',
    tabler: 'IconLoader2',
    fontAwesome: 'faSpinner',
    radix: 'UpdateIcon',
  },
  {
    generic: 'image',
    lucide: 'Image',
    heroicons: 'PhotoIcon',
    phosphor: 'Image',
    tabler: 'IconPhoto',
    fontAwesome: 'faImage',
    radix: 'ImageIcon',
  },
  {
    generic: 'file',
    lucide: 'File',
    heroicons: 'DocumentIcon',
    phosphor: 'File',
    tabler: 'IconFile',
    fontAwesome: 'faFile',
    radix: 'FileIcon',
  },
  {
    generic: 'folder',
    lucide: 'Folder',
    heroicons: 'FolderIcon',
    phosphor: 'Folder',
    tabler: 'IconFolder',
    fontAwesome: 'faFolder',
    radix: 'FileIcon',
  },
];
