import type { IComponentSnippet } from '../types.js';

export const typographySnippets: IComponentSnippet[] = [
  {
    id: 'heading-h1',
    name: 'Page Heading (H1)',
    category: 'atom',
    type: 'heading',
    variant: 'h1',
    tags: ['title', 'hero', 'page-title', 'typography'],
    mood: ['bold', 'editorial', 'professional'],
    industry: ['general'],
    visualStyles: ['minimal-editorial', 'dark-premium', 'corporate-trust'],
    jsx: `<h1 className="scroll-m-20 text-4xl font-bold tracking-tight text-foreground lg:text-5xl">Page Heading</h1>`,
    tailwindClasses: {
      heading: 'scroll-m-20 text-4xl font-bold tracking-tight text-foreground lg:text-5xl',
    },
    a11y: {
      roles: ['heading'],
      ariaAttributes: ['aria-level="1"'],
      keyboardNav: 'N/A',
      contrastRatio: '7:1',
      focusVisible: false,
      reducedMotion: true,
    },
    seo: { semanticElement: 'h1', headingLevel: 'h1' },
    responsive: { strategy: 'mobile-first', breakpoints: ['lg'] },
    quality: {
      antiGeneric: [
        'tracking-tight for editorial feel',
        'scroll-m-20 for anchor link offset',
        'responsive sizing 4xl→5xl',
      ],
      inspirationSource: 'shadcn/ui Typography',
      craftDetails: ['tight tracking for large headings', 'scroll-margin for sticky header offset'],
    },
  },
  {
    id: 'heading-h2',
    name: 'Section Heading (H2)',
    category: 'atom',
    type: 'heading',
    variant: 'h2',
    tags: ['section', 'title', 'typography'],
    mood: ['professional', 'editorial'],
    industry: ['general'],
    visualStyles: ['minimal-editorial', 'dark-premium', 'corporate-trust'],
    jsx: `<h2 className="scroll-m-20 text-3xl font-semibold tracking-tight text-foreground first:mt-0">Section Title</h2>`,
    tailwindClasses: {
      heading: 'scroll-m-20 text-3xl font-semibold tracking-tight text-foreground first:mt-0',
    },
    a11y: {
      roles: ['heading'],
      ariaAttributes: ['aria-level="2"'],
      keyboardNav: 'N/A',
      contrastRatio: '7:1',
      focusVisible: false,
      reducedMotion: true,
    },
    seo: { semanticElement: 'h2', headingLevel: 'h2' },
    responsive: { strategy: 'mobile-first', breakpoints: ['lg'] },
    quality: {
      antiGeneric: ['font-semibold not bold — hierarchy differentiation from h1', 'first:mt-0 prevents double spacing'],
      inspirationSource: 'shadcn/ui Typography',
      craftDetails: [
        'weight hierarchy: h1=bold, h2=semibold, h3=semibold smaller',
        'scroll-m-20 consistent with h1 for anchor links',
      ],
    },
  },
  {
    id: 'heading-h3',
    name: 'Subsection Heading (H3)',
    category: 'atom',
    type: 'heading',
    variant: 'h3',
    tags: ['subsection', 'title', 'typography'],
    mood: ['professional'],
    industry: ['general'],
    visualStyles: ['minimal-editorial', 'soft-depth', 'corporate-trust'],
    jsx: `<h3 className="scroll-m-20 text-2xl font-semibold tracking-tight text-foreground">Subsection</h3>`,
    tailwindClasses: {
      heading: 'scroll-m-20 text-2xl font-semibold tracking-tight text-foreground',
    },
    a11y: {
      roles: ['heading'],
      ariaAttributes: ['aria-level="3"'],
      keyboardNav: 'N/A',
      contrastRatio: '7:1',
      focusVisible: false,
      reducedMotion: true,
    },
    seo: { semanticElement: 'h3', headingLevel: 'h3' },
    responsive: { strategy: 'mobile-first', breakpoints: [] },
    quality: {
      antiGeneric: ['consistent tracking-tight across heading levels', 'text-2xl differentiates from h2 at 3xl'],
      inspirationSource: 'shadcn/ui Typography',
      craftDetails: ['clear size hierarchy: 5xl→3xl→2xl', 'no responsive scaling — subsections stay compact'],
    },
  },
  {
    id: 'paragraph-default',
    name: 'Body Paragraph',
    category: 'atom',
    type: 'paragraph',
    variant: 'default',
    tags: ['text', 'body', 'media', 'typography'],
    mood: ['professional', 'minimal', 'calm'],
    industry: ['general'],
    visualStyles: ['minimal-editorial', 'soft-depth', 'corporate-trust'],
    jsx: `<p className="text-base leading-7 text-muted-foreground [&:not(:first-child)]:mt-6">Body text with comfortable reading line height and proper paragraph spacing.</p>`,
    tailwindClasses: {
      paragraph: 'text-base leading-7 text-muted-foreground [&:not(:first-child)]:mt-6',
    },
    a11y: {
      roles: [],
      ariaAttributes: [],
      keyboardNav: 'N/A',
      contrastRatio: '4.5:1',
      focusVisible: false,
      reducedMotion: true,
    },
    seo: { semanticElement: 'p' },
    responsive: { strategy: 'mobile-first', breakpoints: [] },
    quality: {
      antiGeneric: [
        'leading-7 for readable line height',
        'muted-foreground for hierarchy',
        'paragraph spacing via arbitrary variant',
      ],
      inspirationSource: 'shadcn/ui Typography',
      craftDetails: ['leading-7 (1.75rem) for comfortable reading', 'auto paragraph spacing'],
    },
  },
  {
    id: 'paragraph-lead',
    name: 'Lead Paragraph',
    category: 'atom',
    type: 'paragraph',
    variant: 'lead',
    tags: ['intro', 'subtitle', 'lead', 'typography'],
    mood: ['editorial', 'premium'],
    industry: ['general', 'agency', 'media'],
    visualStyles: ['minimal-editorial', 'dark-premium'],
    jsx: `<p className="text-xl text-muted-foreground leading-relaxed">A lead paragraph that introduces the content with larger, lighter text for visual hierarchy.</p>`,
    tailwindClasses: {
      paragraph: 'text-xl text-muted-foreground leading-relaxed',
    },
    a11y: {
      roles: [],
      ariaAttributes: [],
      keyboardNav: 'N/A',
      contrastRatio: '4.5:1',
      focusVisible: false,
      reducedMotion: true,
    },
    seo: { semanticElement: 'p' },
    responsive: { strategy: 'mobile-first', breakpoints: [] },
    quality: {
      antiGeneric: ['text-xl for prominence', 'leading-relaxed for readability at larger size'],
      inspirationSource: 'Medium article leads',
      craftDetails: ['relaxed line-height at xl size', 'muted-foreground for subordination to heading'],
    },
  },
  {
    id: 'blockquote-default',
    name: 'Blockquote',
    category: 'atom',
    type: 'blockquote',
    variant: 'default',
    tags: ['quote', 'citation', 'testimonial', 'typography'],
    mood: ['editorial', 'professional'],
    industry: ['general', 'media', 'agency'],
    visualStyles: ['minimal-editorial', 'soft-depth'],
    jsx: `<blockquote className="mt-6 border-l-4 border-primary/30 pl-6 text-muted-foreground italic leading-7">
  "Design is not just what it looks like and feels like. Design is how it works."
</blockquote>`,
    tailwindClasses: {
      blockquote: 'mt-6 border-l-4 border-primary/30 pl-6 text-muted-foreground italic leading-7',
    },
    a11y: {
      roles: [],
      ariaAttributes: [],
      keyboardNav: 'N/A',
      contrastRatio: '4.5:1',
      focusVisible: false,
      reducedMotion: true,
    },
    seo: { semanticElement: 'blockquote' },
    responsive: { strategy: 'mobile-first', breakpoints: [] },
    quality: {
      antiGeneric: ['border-primary/30 for subtle color accent', 'pl-6 generous indent', 'italic for quote convention'],
      inspirationSource: 'Novel editor blockquote',
      craftDetails: ['border-l-4 for clear visual marker', 'primary/30 tint not solid'],
    },
  },
  {
    id: 'code-inline',
    name: 'Inline Code',
    category: 'atom',
    type: 'code',
    variant: 'inline',
    tags: ['code', 'monospace', 'technical', 'typography'],
    mood: ['professional'],
    industry: ['devtools', 'saas', 'education'],
    visualStyles: ['linear-modern', 'soft-depth'],
    jsx: `<code className="relative rounded-md bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm font-medium text-foreground">code</code>`,
    tailwindClasses: {
      code: 'relative rounded-md bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm font-medium text-foreground',
    },
    a11y: {
      roles: [],
      ariaAttributes: [],
      keyboardNav: 'N/A',
      contrastRatio: '4.5:1',
      focusVisible: false,
      reducedMotion: true,
    },
    seo: { semanticElement: 'code' },
    responsive: { strategy: 'mobile-first', breakpoints: [] },
    quality: {
      antiGeneric: ['bg-muted for clear distinction', 'font-mono for code convention', 'precise padding values'],
      inspirationSource: 'Novel editor inline code',
      craftDetails: ['sub-pixel padding for tight fit', 'font-medium for readability at small size'],
    },
  },
];
