name: "Setup siza-gen"
description: "Clone and build @forgespace/siza-gen as sibling directory for file: protocol resolution"

runs:
  using: "composite"
  steps:
    - name: Clone and build siza-gen
      shell: bash
      run: |
        if [ ! -d "../siza-gen" ]; then
          git clone --depth 1 https://github.com/Forge-Space/siza-gen.git ../siza-gen
          cd ../siza-gen
          for i in 1 2 3; do
            npm install --legacy-peer-deps --fetch-retries=5 && break
            echo "npm install attempt $i failed, retrying..."
            sleep 5
          done
          npm run build
        fi
