name: Base CI Workflow (Shared Patterns)

on:
  workflow_call:
    inputs:
      project-type:
        description: 'Type of project (gateway, webapp, mcp)'
        required: false
        default: 'gateway'
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '22'
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.12'
      enable-docker:
        description: 'Enable Docker builds'
        required: false
        default: true
      enable-security:
        description: 'Enable security scanning'
        required: false
        default: true
      enable-coverage:
        description: 'Enable coverage reporting'
        required: false
        default: true
      coverage-threshold:
        description: 'Coverage threshold percentage'
        required: false
        default: '80'
      test-parallel:
        description: 'Run tests in parallel'
        required: false
        default: true
    secrets:
      CODECOV_TOKEN:
        description: 'Codecov token'
        required: false
      SNYK_TOKEN:
        description: 'Snyk token'
        required: false
      GITHUB_TOKEN:
        description: 'GitHub token'
        required: false

jobs:
  # Setup jobs
  setup-node:
    name: Setup Node.js
    uses: ./.github/workflows/reusable/setup-node.yml
    with:
      node-version: ${{ inputs.node-version }}
      enable-cache: true
    if: inputs.project-type == 'webapp' || inputs.project-type == 'mcp'

  setup-python:
    name: Setup Python
    uses: ./.github/workflows/reusable/setup-python.yml
    with:
      python-version: ${{ inputs.python-version }}
      enable-cache: true
      requirements-files: 'requirements.txt apps/tool-router/requirements.txt'
    if: inputs.project-type == 'gateway'

  # Linting jobs
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    needs: setup-python
    if: inputs.project-type == 'gateway'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install ruff black mypy
          pip install -r requirements.txt

      - name: Run Ruff linting
        run: |
          ruff check apps/ src/ scripts/ --format=github

      - name: Run Black formatting check
        run: |
          black --check apps/ src/ scripts/

      - name: Run MyPy type checking
        run: |
          mypy apps/tool-router/src/ --ignore-missing-imports || true

  lint-typescript:
    name: Lint TypeScript
    runs-on: ubuntu-latest
    needs: setup-node
    if: inputs.project-type == 'webapp' || inputs.project-type == 'mcp'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run ESLint
        run: |
          npm run lint || npx eslint apps/web-admin/src/ --ext .ts,.tsx

      - name: Run TypeScript check
        run: |
          npm run type-check || npx tsc --noEmit

  lint-shell:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: |
          find . -name "*.sh" -exec shellcheck {} \;

  # Testing jobs
  test-python:
    name: Test Python
    runs-on: ubuntu-latest
    needs: setup-python
    if: inputs.project-type == 'gateway'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov pytest-mock
          pip install -r requirements.txt
          pip install -r apps/tool-router/requirements.txt

      - name: Run tests with coverage
        run: |
          pytest apps/tool-router/tests/ \
            --cov=apps/tool-router/src \
            --cov-report=xml \
            --cov-report=html \
            --cov-report=term-missing \
            --cov-fail-under=${{ inputs.coverage-threshold }}

      - name: Upload coverage
        if: inputs.enable-coverage
        uses: ./.github/workflows/reusable/upload-coverage.yml
        with:
          coverage-files: './coverage.xml,./htmlcov/'
          flags: 'python-tests'
          name: 'python-coverage'
        secrets:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-typescript:
    name: Test TypeScript
    runs-on: ubuntu-latest
    needs: setup-node
    if: inputs.project-type == 'webapp' || inputs.project-type == 'mcp'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          npm test || npm run test:unit

      - name: Upload coverage
        if: inputs.enable-coverage
        uses: ./.github/workflows/reusable/upload-coverage.yml
        with:
          coverage-files: './coverage/lcov.info,./coverage/'
          flags: 'typescript-tests'
          name: 'typescript-coverage'
        secrets:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Build jobs
  build-python:
    name: Build Python
    runs-on: ubuntu-latest
    needs: [lint-python, test-python]
    if: inputs.project-type == 'gateway'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install build dependencies
        run: |
          pip install build twine
          pip install -r requirements.txt

      - name: Build package
        run: |
          python -m build

  build-typescript:
    name: Build TypeScript
    runs-on: ubuntu-latest
    needs: [lint-typescript, test-typescript]
    if: inputs.project-type == 'webapp' || inputs.project-type == 'mcp'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build application
        run: |
          npm run build

  # Docker build job
  build-docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [build-python, build-typescript]
    if: inputs.enable-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          if [ "${{ inputs.project-type }}" = "gateway" ]; then
            docker-compose -f docker-compose.yml build
            docker-compose -f docker/docker-compose.dev.yml build
          else
            echo "Docker build for ${{ inputs.project-type }} not implemented yet"
          fi

  # Security scanning
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [lint-python, lint-typescript, lint-shell]
    if: inputs.enable-security

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Snyk security scan
        if: secrets.SNYK_TOKEN
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
